"use client"

import React, { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Send, Bot, User, Sparkles } from 'lucide-react'
import { playTick, playPopover, playNotification } from '@/lib/sounds'

interface Message {
  id: number
  text: string
  sender: 'user' | 'bot'
  timestamp: Date
}

// ── Portfolio Knowledge Base ──────────────────────────────────────────
const PORTFOLIO_DATA = {
  name: 'Dhruv Dinesh Patil',
  role: 'AI Researcher & Generative Model Engineer',
  location: 'Nagpur, Maharashtra, India',
  email: 'sujalpatil8657231278@gmail.com',
  phone: '+91 8857841863',
  cgpa: '8.76',
  leetcodeRank: '370,720',
  resumeUrl: '/dhruv-patil-resume.pdf',

  socials: {
    github: 'https://github.com/DhruvPatil123',
    twitter: 'https://x.com/DhruvPatil_18',
    linkedin: 'https://www.linkedin.com/in/dhruv-patil-3816043b7/',
    instagram: 'https://www.instagram.com/_dhruv.exe.18',
    leetcode: 'https://leetcode.com/u/Dhruv_Patil_18/',
  },

  skills: {
    ai: ['PyTorch', 'TensorFlow', 'Hugging Face', 'LangChain', 'LlamaIndex', 'RAG', 'LLMs', 'Agentic Workflows', 'Computer Vision'],
    web: ['React 19', 'Next.js', 'Node.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'Tailwind CSS', 'Firebase', 'WebSockets'],
    systems: ['C++', 'Java (Advanced)', '.NET Core', 'C#', 'Cryptography', 'Software Testing', 'Git', 'Figma Prototyping'],
  },

  education: [
    { degree: 'B.Tech — Artificial Intelligence', institution: 'J.D. College of Engineering and Management, Nagpur', year: '2025 - 2028', cgpa: '8.76' },
    { degree: 'Diploma — Computer Science', institution: 'NIT Polytechnic, Nagpur', year: '2022 - 2025', score: '78%' },
    { degree: 'Secondary Education (10th)', institution: 'Yugantar High School, Nagpur', year: '2022', score: '81%' },
  ],

  projects: [
    { name: 'Raincrew.AI', desc: 'AI Talent Acquisition & Biometric Proctoring Engine using Google Gemini Multimodal Live WebSocket API', category: 'GenAI / Multimodal' },
    { name: 'AutoForge.AI', desc: 'Autonomous software engineering agent orchestrating planning, sandboxed code execution, and self-healing test cycles', category: 'Agentic AI' },
    { name: 'VisionCraft.AI', desc: 'Text-to-image and generative video app using GANs for 2K/4K output', category: 'Generative Art' },
    { name: 'SchemaForge.AI', desc: 'Natural language to universal database schema compiler featuring real-time interactive ERD visualizers', category: 'LLM Compiler' },
    { name: 'WaterFlow', desc: 'Intelligent theme and UX composition engine translating abstract prompt thoughts into fully interactive, fluid digital experiences', category: 'Generative UX' },
    { name: 'AI Hallucination Detector', desc: 'High-precision evaluation system detecting factually incorrect or inconsistent statements generated by large language models', category: 'LLM Eval' },
    { name: 'AI Study Planner', desc: 'Complete student-success planner utilizing LLMs to synthesize personalized study tracks, resource guides, and milestone goals', category: 'Full-Stack' },
    { name: 'ResuNova', desc: 'Immersive AI-powered resume builder combining an animated 3D frontend with a Streamlit-Python optimization backend', category: 'AI Resume Engine' },
    { name: 'EncryptX', desc: 'Multi-layered encryption toolkit (AES, DES, RSA) with native hardware acceleration', category: 'Cryptography' },
    { name: 'Dockmind', desc: 'Enterprise-grade Retrieval-Augmented Generation (RAG) chatbot and multi-format file querying engine', category: 'GenAI / RAG' },
  ],

  certifications: [
    'Generative AI, Deep Learning & LLMs — EduSkills / AICTE',
    'Professional UI/UX Design & Web Prototyping — EduSkills / AICTE',
    'Enhancing Soft Skills & Personality — NPTEL (IIT Kanpur)',
    'Full-Stack Flask Development Mastery — L&T EduTech',
  ],
}

// ── Intent Matching ──────────────────────────────────────────────────
function generateResponse(input: string): string {
  const q = input.toLowerCase().trim()

  // Greetings
  if (/^(hi|hello|hey|yo|sup|what'?s? up|howdy|hola)/i.test(q)) {
    return `Hey there! 👋 I'm Dhruv's portfolio assistant. I can help with **skills**, **projects**, **education**, **certifications**, **resume**, or **contact info**. What would you like to know?`
  }

  // Name / Who
  if (/who (is|are)|your name|about (you|dhruv|him)|tell me about|introduce/i.test(q)) {
    return `**${PORTFOLIO_DATA.name}** is an AI Researcher & Generative Model Engineer based in ${PORTFOLIO_DATA.location}. He's pursuing a B.Tech in Artificial Intelligence with a CGPA of ${PORTFOLIO_DATA.cgpa}, specializing in LLMs, Agentic AI, and RAG systems. 🚀`
  }

  // Skills
  if (/skill|tech|stack|what (can|does) (he|dhruv) (do|know|use)|expertise|proficien/i.test(q)) {
    return `Dhruv's technical arsenal spans three domains:\n\n🤖 **AI & ML:** ${PORTFOLIO_DATA.skills.ai.join(', ')}\n\n🌐 **Web Engineering:** ${PORTFOLIO_DATA.skills.web.join(', ')}\n\n⚙️ **Systems & Security:** ${PORTFOLIO_DATA.skills.systems.join(', ')}`
  }

  // AI-specific skills
  if (/\b(ai|machine learning|ml|deep learning|llm|gpt|genai|generative|agentic|rag|nlp|computer vision|pytorch|tensorflow|langchain|hugging)/i.test(q)) {
    return `In AI & ML, Dhruv works with:\n\n${PORTFOLIO_DATA.skills.ai.map(s => `• ${s}`).join('\n')}\n\nHis focus areas are **LLMs, Agentic Workflows, and RAG** for building autonomous AI systems. 🧠`
  }

  // Web skills
  if (/\b(web|react|next|node|frontend|backend|fullstack|full-stack|typescript|fastapi|api)/i.test(q)) {
    return `For web engineering, Dhruv uses:\n\n${PORTFOLIO_DATA.skills.web.map(s => `• ${s}`).join('\n')}\n\nHe builds high-performance web apps with React 19, Next.js, and FastAPI backends. 💻`
  }

  // Projects (general)
  if (/project|work|portfolio|built|created|developed|made/i.test(q)) {
    const projectList = PORTFOLIO_DATA.projects.map(p => `• **${p.name}** _(${p.category})_ — ${p.desc}`).join('\n')
    return `Dhruv has built ${PORTFOLIO_DATA.projects.length} notable projects:\n\n${projectList}\n\nAsk about any specific project for more details! 🔥`
  }

  // Specific project queries
  if (/raincrew/i.test(q)) return `🎯 **Raincrew.AI** is Dhruv's flagship project — a next-gen AI Talent Acquisition & Biometric Proctoring Engine using Google Gemini Multimodal Live WebSocket API with real-time oral interview metrics. It's in the GenAI / Multimodal space.`
  if (/autoforge/i.test(q)) return `🛠️ **AutoForge.AI** is an autonomous software engineering agent combining LLMs, agentic planning, and sandboxed execution to write, compile, test, and repair production-ready code blocks autonomously.`
  if (/visioncraft/i.test(q)) return `🎨 **VisionCraft.AI** is a text-to-image and generative video application using custom prompt modeling via GANs to produce 2K/4K visual output.`
  if (/schemaforge/i.test(q)) return `🗄️ **SchemaForge.AI** is a natural language to universal database schema generator that parses simple English descriptions into PostgreSQL/MySQL structures and draws interactive relational ERD graphs.`
  if (/waterflow/i.test(q)) return `💧 **WaterFlow** is an immersive design compiler that translates abstract thoughts and mood parameters into functional, highly-polished web interfaces with fluid responsive spacing and themes.`
  if (/hallucination/i.test(q)) return `🔍 **AI Hallucination Detector** is an NLP diagnostic suite designed to evaluate model reliability by extracting proposition claims and measuring inconsistency markers against verified grounding pools.`
  if (/study.planner|planner/i.test(q)) return `📅 **AI Study Planner** is an AI student-success companion that creates optimized calendars, review flashcards, and spaced-repetition schedules from raw curriculums.`
  if (/resunova/i.test(q)) return `📄 **ResuNova** is a premium, AI-driven resume optimizer utilizing Streamlit-Python backends and 3D graphics to generate ATS-compatible, impact-metric-enriched professional documents.`
  if (/encrypt/i.test(q)) return `🔐 **EncryptX** is a security desktop toolkit implementing multi-layered encryption algorithms including AES, DES, and RSA.`
  if (/dockmind/i.test(q)) return `🐳 **Dockmind** is an enterprise-grade file-querying Retrieval-Augmented Generation (RAG) chatbot application. It supports uploading massive multi-format files (PDF, DOCX, TXT), segments document content using semantic chunking, indexes embeddings in an optimized vector database, and supports real-time conversational retrieval powered by LLM models with dynamic source citation highlights.`

  if (/resume|cv|download|profile/i.test(q)) {
    return `You can download Dhruv's resume from the hero section or open it directly here:\n\n${PORTFOLIO_DATA.resumeUrl}\n\nIt highlights his AI research focus, web stack, education, and selected projects.`
  }

  if (/hire|recruit|candidate|fit|strength|why dhruv/i.test(q)) {
    return `Dhruv is strongest for roles that need **AI prototyping plus production web execution**. His portfolio combines LLM/RAG systems, multimodal GenAI projects, TypeScript/Next.js interfaces, and solid fundamentals from C++, Java, and software testing.`
  }

  // Education
  if (/educat|college|university|degree|school|diploma|study|cgpa|gpa|academic/i.test(q)) {
    const eduList = PORTFOLIO_DATA.education.map(e => `🎓 **${e.degree}**\n   ${e.institution} _(${e.year})_`).join('\n\n')
    return `Dhruv's academic background:\n\n${eduList}\n\nCurrent CGPA: **${PORTFOLIO_DATA.cgpa}** ⭐`
  }

  // Certifications
  if (/certif|course|training|credential/i.test(q)) {
    const certList = PORTFOLIO_DATA.certifications.map(c => `✅ ${c}`).join('\n')
    return `Dhruv holds these certifications:\n\n${certList}`
  }

  // Contact
  if (/contact|email|mail|phone|call|reach|hire|connect|talk/i.test(q)) {
    return `You can reach Dhruv through:\n\n📧 **Email:** ${PORTFOLIO_DATA.email}\n📱 **Phone:** ${PORTFOLIO_DATA.phone}\n📍 **Location:** ${PORTFOLIO_DATA.location}\n\nOr connect on social media — links are in the footer! 🤝`
  }

  // Social links
  if (/social|github|twitter|linkedin|instagram|leetcode/i.test(q)) {
    return `Dhruv's social profiles:\n\n🐙 **GitHub:** ${PORTFOLIO_DATA.socials.github}\n🐦 **Twitter/X:** ${PORTFOLIO_DATA.socials.twitter}\n💼 **LinkedIn:** ${PORTFOLIO_DATA.socials.linkedin}\n📸 **Instagram:** ${PORTFOLIO_DATA.socials.instagram}\n💡 **LeetCode:** ${PORTFOLIO_DATA.socials.leetcode}`
  }

  // LeetCode
  if (/leetcode|competitive|coding|rank/i.test(q)) {
    return `Dhruv's LeetCode profile:\n\n🏆 **Global Rank:** ${PORTFOLIO_DATA.leetcodeRank}\n🔗 **Profile:** ${PORTFOLIO_DATA.socials.leetcode}\n\nHe has solved 360+ algorithmic challenges! 💪`
  }

  // Location
  if (/where|location|city|country|based/i.test(q)) {
    return `Dhruv is based in **${PORTFOLIO_DATA.location}** 📍`
  }

  // Experience / internships
  if (/experience|intern|job|work history|career/i.test(q)) {
    return `Dhruv's professional experience includes:\n\n💼 **GenAI & Deep Learning Intern** — EduSkills Foundation / AICTE (Jan–Mar 2026)\nSpecialized in GANs, Deep Learning architectures, and LLM pipeline optimization.\n\n🎨 **UI/UX Design & Web Prototyping Intern** — EduSkills Foundation / AICTE (Apr–Jun 2026)\nDeveloped high-fidelity wireframes and functional digital prototypes.\n\n🛠️ **Enterprise Flask Backend Certified** — L&T EduTech (May 2026)\nMastered production SQL routing, RESTful architecture, and multi-threaded processing.`
  }

  // Thanks
  if (/thank|thanks|thx|appreciate/i.test(q)) {
    return `You're welcome! 😊 If you'd like to work with Dhruv or have any more questions, feel free to ask or drop him an email at **${PORTFOLIO_DATA.email}**!`
  }

  // Goodbye
  if (/bye|goodbye|see you|later|cya/i.test(q)) {
    return `Goodbye! 👋 Thanks for visiting Dhruv's portfolio. Don't hesitate to reach out if you need anything!`
  }

  // Fallback
  return `Great question! I can help you with info about Dhruv's:\n\n• **Skills** — AI/ML, Web, Systems\n• **Projects** — 9 notable builds\n• **Education** — Academic background\n• **Certifications** — Professional credentials\n• **Contact** — How to reach Dhruv\n• **Experience** — Internships & career\n\nTry asking about any of these! 💡`
}

// ── Chatbot Component ────────────────────────────────────────────────
interface ChatbotProps {
  isOpen: boolean
  onClose: () => void
}

export default function Chatbot({ isOpen, onClose }: ChatbotProps) {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    setMessages([
      {
        id: 0,
        text: "Hey! 👋 I'm Dhruv's portfolio assistant. Ask me anything about his **skills**, **projects**, **education**, or **contact info**!",
        sender: 'bot',
        timestamp: new Date(),
      },
    ])
  }, [])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages, isTyping])

  useEffect(() => {
    if (isOpen) {
      playPopover()
      setTimeout(() => inputRef.current?.focus(), 300)
    }
  }, [isOpen])

  const handleSend = async () => {
    const trimmed = input.trim()
    if (!trimmed) return

    playTick()

    const userMsg: Message = {
      id: Date.now(),
      text: trimmed,
      sender: 'user',
      timestamp: new Date(),
    }

    const updatedMessages = [...messages, userMsg]
    setMessages(updatedMessages)
    setInput('')
    setIsTyping(true)

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: updatedMessages }),
      })

      if (!response.ok) {
        throw new Error('API failed')
      }

      const data = await response.json()
      const botMsg: Message = {
        id: Date.now() + 1,
        text: data.text,
        sender: 'bot',
        timestamp: new Date(),
      }

      setIsTyping(false)
      setMessages((prev) => [...prev, botMsg])
      playNotification()
    } catch (error) {
      console.warn('Dynamic chat failing, falling back to local database:', error)
      // Simulate typing delay
      const delay = Math.min(800 + trimmed.length * 10, 1500)
      await new Promise((res) => setTimeout(res, delay))

      const botResponse = generateResponse(trimmed)
      const botMsg: Message = {
        id: Date.now() + 1,
        text: botResponse,
        sender: 'bot',
        timestamp: new Date(),
      }

      setIsTyping(false)
      setMessages((prev) => [...prev, botMsg])
      playNotification()
    }
  }

  const sendPrompt = async (query: string, displayText?: string) => {
    playTick()

    const userMsg: Message = {
      id: Date.now(),
      text: displayText || query,
      sender: 'user',
      timestamp: new Date(),
    }

    const updatedMessages = [...messages, userMsg]
    setMessages(updatedMessages)
    setInput('')
    setIsTyping(true)

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: updatedMessages }),
      })

      if (!response.ok) {
        throw new Error('API failed')
      }

      const data = await response.json()
      setIsTyping(false)
      setMessages((prev) => [
        ...prev,
        { id: Date.now() + 1, text: data.text, sender: 'bot', timestamp: new Date() },
      ])
      playNotification()
    } catch (error) {
      console.warn('Dynamic prompt failing, falling back to local database:', error)
      setTimeout(() => {
        const botResponse = generateResponse(query)
        setIsTyping(false)
        setMessages((prev) => [
          ...prev,
          { id: Date.now() + 1, text: botResponse, sender: 'bot', timestamp: new Date() },
        ])
        playNotification()
      }, 1000)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  // Improved markdown-like rendering for rich text
  const renderText = (text: string) => {
    const lines = text.split('\n')
    return (
      <div className="space-y-1.5 font-sans text-sm">
        {lines.map((line, idx) => {
          let content: React.ReactNode = line

          // Check if it is a list item or bullet point
          const isBullet = line.trim().startsWith('•') || line.trim().startsWith('-') || line.trim().startsWith('*')
          const cleanLine = isBullet ? line.replace(/^[\s•\-*]+/, '') : line

          // Parse bold text **text**
          const parts = cleanLine.split(/(\*\*[^*]+\*\*)/g)
          const parsedParts = parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return (
                <strong key={i} className="text-white font-bold font-sans">
                  {part.slice(2, -2)}
                </strong>
              )
            }
            // Parse inline code `code`
            const codeParts = part.split(/(`[^`]+`)/g)
            return codeParts.map((cPart, cIdx) => {
              if (cPart.startsWith('`') && cPart.endsWith('`')) {
                return (
                  <code key={`${i}-${cIdx}`} className="px-1.5 py-0.5 rounded bg-white/10 text-primary font-mono text-xs font-semibold">
                    {cPart.slice(1, -1)}
                  </code>
                )
              }
              return cPart
            })
          })

          if (isBullet) {
            content = (
              <div key={idx} className="flex gap-2 items-start pl-2">
                <span className="text-primary mt-1 shrink-0">•</span>
                <span className="flex-1 text-gray-300 font-sans">{parsedParts}</span>
              </div>
            )
          } else {
            content = (
              <p key={idx} className="text-gray-300 font-sans leading-relaxed">
                {parsedParts}
              </p>
            )
          }

          return content
        })}
      </div>
    )
  }

  const quickQuestions = [
    { label: '🏆 LeetCode Rank', query: 'LeetCode Rank' },
    { label: '🚀 Top Projects', query: 'Best AI projects?' },
    { label: '📬 Let\'s Connect', query: 'How to contact?' },
    { label: '💼 Experience', query: 'Experience' },
    { label: '🎓 Education', query: 'Education' },
  ]

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[998]"
          />

          {/* Chat Panel */}
          <motion.div
            initial={{ opacity: 0, y: 40, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 40, scale: 0.95 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="fixed bottom-4 left-4 right-4 md:left-auto md:right-8 md:bottom-8 md:w-[440px] h-[520px] md:h-[600px] max-h-[85vh] z-[999] flex flex-col rounded-3xl overflow-hidden border border-white/15"
            style={{
              background: 'linear-gradient(145deg, rgba(10,10,10,0.95), rgba(20,20,30,0.95))',
              backdropFilter: 'blur(24px)',
              boxShadow: '0 0 60px rgba(0,242,255,0.08), 0 25px 50px rgba(0,0,0,0.5)',
            }}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
              <div className="flex items-center gap-3">
                <div className="relative">
                  <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-dark" />
                  </div>
                  <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-green-400 rounded-full border-2 border-dark" />
                </div>
                <div>
                  <h3 className="text-white font-bold text-sm">Portfolio Assistant</h3>
                  <p className="text-green-400 text-[10px] uppercase tracking-widest font-medium">Online</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="w-8 h-8 rounded-xl bg-white/5 hover:bg-white/10 flex items-center justify-center text-gray-400 hover:text-white transition-all"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4 scrollbar-thin">
              {messages.map((msg) => (
                <motion.div
                  key={msg.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3 }}
                  className={`flex gap-2.5 ${msg.sender === 'user' ? 'flex-row-reverse' : ''}`}
                >
                  <div
                    className={`w-7 h-7 rounded-xl flex items-center justify-center flex-shrink-0 mt-1 ${
                      msg.sender === 'bot'
                        ? 'bg-gradient-to-br from-primary/20 to-secondary/20 text-primary'
                        : 'bg-white/10 text-white'
                    }`}
                  >
                    {msg.sender === 'bot' ? <Bot className="w-3.5 h-3.5" /> : <User className="w-3.5 h-3.5" />}
                  </div>
                  <div
                    className={`max-w-[80%] px-4 py-3 rounded-2xl text-sm leading-relaxed ${
                      msg.sender === 'bot'
                        ? 'bg-white/5 text-gray-300 rounded-tl-md border border-white/5'
                        : 'bg-gradient-to-r from-primary to-primary/80 text-dark font-medium rounded-tr-md'
                    }`}
                  >
                    {renderText(msg.text)}
                  </div>
                </motion.div>
              ))}

              {/* Typing Indicator */}
              {isTyping && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex gap-2.5"
                >
                  <div className="w-7 h-7 rounded-xl bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center text-primary flex-shrink-0 mt-1">
                    <Bot className="w-3.5 h-3.5" />
                  </div>
                  <div className="bg-white/5 border border-white/5 px-4 py-3 rounded-2xl rounded-tl-md flex items-center">
                    <div className="flex gap-1.5 items-center py-1">
                      {[0, 1, 2].map((index) => (
                        <motion.span
                          key={index}
                          className="w-2 h-2 bg-primary rounded-full"
                          animate={{
                            y: ["0%", "-50%", "0%"]
                          }}
                          transition={{
                            duration: 0.6,
                            repeat: Infinity,
                            repeatType: "loop",
                            ease: "easeInOut",
                            delay: index * 0.15,
                          }}
                        />
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Interactive Quick-Reply Chips */}
            <div 
              className="px-4 py-2 border-t border-white/5 bg-black/10 overflow-x-auto scrollbar-none"
              style={{
                scrollbarWidth: 'none',
                msOverflowStyle: 'none',
              }}
            >
              <div className="flex gap-2 flex-nowrap pb-0.5">
                {quickQuestions.map((q) => (
                  <button
                    key={q.label}
                    onClick={() => sendPrompt(q.query, q.label)}
                    className="px-3 py-1.5 rounded-full text-[11px] font-medium bg-white/5 text-zinc-300 hover:text-primary hover:bg-primary/10 border border-white/5 hover:border-primary/30 transition-all duration-300 shadow-sm flex items-center gap-1.5 whitespace-nowrap active:scale-95 cursor-pointer hover:shadow-[0_0_12px_rgba(0,242,255,0.12)]"
                  >
                    {q.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Input */}
            <div className="px-4 pb-4 pt-2">
              <div className="flex items-center gap-2 bg-white/5 border border-white/10 rounded-2xl px-4 py-2 focus-within:border-primary/50 transition-colors">
                <input
                  ref={inputRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Ask about Dhruv..."
                  className="flex-1 bg-transparent text-white text-sm outline-none placeholder:text-gray-600"
                />
                <button
                  onClick={handleSend}
                  disabled={!input.trim()}
                  className={`w-8 h-8 rounded-xl flex items-center justify-center transition-all ${
                    input.trim()
                      ? 'bg-primary text-dark hover:scale-105'
                      : 'bg-white/5 text-gray-600'
                  }`}
                >
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}
